locale: "en-US"
title: "ADai's Homepage"
title_separator: "-"
name: "Shiwen Liu"
description: "Shiwen Liu's academic portfolio"
url: "https://ShvenLyons.github.io"
baseurl: ""
repository: "ShvenLyons/ShvenLyons.github.io"

author:
  avatar: "profile.png"
  name: "SHIWEN LIU"
  location: "Guangzhou, China"
  employer: "HKUST(GZ)"
  uri: "https://www.bristol.ac.uk/"
  email: "shiwen.liu.2022@bristol.ac.uk"
  googlescholar: "https://scholar.google.com/citations?user=nzRuAl8AAAAJ"
  orcid: "https://orcid.org/0009-0009-6114-9873"
  github: "ShvenLyons"

include:
  - _pages
  - files

exclude:
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - LICENSE
  - node_modules
  - README.md
  - vendor

keep_files:
  - .git

encoding: "utf-8"
markdown: kramdown
highlighter: rouge
future: true
permalink: /:title/
timezone: Etc/UTC

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  style: compressed

plugins:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
